### ISSUE TITLE
Missing task list status when no items completed

### ISSUE THREAD

**Issue by davwheat** [SychO9/flarum-github-milestone#6]
![image](https://user-images.githubusercontent.com/7406822/117216595-f42c3f80-adf7-11eb-8bf9-49a5508c573d.png)

~~Likely a simple issue with a conditional render.~~ Nevermind, it's in a translation!

**Comment by SychO9** [comment]
woah 🙈

**Comment by davwheat** [comment]
Actually... might be an issue with core!

https://github.com/SychO9/flarum-github-milestone/blob/92e825e34095836799ec23493e92adbae0f6911d/js/src/forum/components/IssueListItem.js#L79-L82

**Comment by davwheat** [comment]
Is fixed in core between build 16 and build 17
